# Generated by Django 6.0.7 on 2026-08-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_phone_appointment_phone_number_and_more'),
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.PositiveIntegerField(),
        ),
    ]
