# Generated by Django 6.0.7 on 2026-08-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_alter_queue_appointment_alter_queue_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.IntegerField(),
        ),
    ]
