# Generated by Django 6.0.7 on 2026-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
