# Generated by Django 6.0.7 on 2026-08-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                
                ('duration', models.IntegerField()),
            ],
        ),
    ]
