# Generated by Django 6.0.7 on 2026-08-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
