# Generated by Django 6.0.7 on 2026-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('completed_tokens', models.PositiveIntegerField(default=0)),
                ('cancelled_tokens', models.PositiveIntegerField(default=0)),
                ('average_wait_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('generated_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
