# Generated by Django 6.0.7 on 2026-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='average_wait_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='cancelled_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
