# Generated by Django 6.0.7 on 2026-08-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_location'),
        ('locations', '0001_initial'),
        ('services', '0003_servicecategory_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
