# Generated by Django 6.0.7 on 2026-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
