# Generated by Django 6.0.7 on 2026-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('General', 'General'), ('Queue', 'Queue'), ('Service', 'Service'), ('Emergency', 'Emergency')], default='General', max_length=20),
        ),
    ]
